@startuml
' Диаграмма активности для процесса бронирования

start
:Пользователь выбирает "Забронировать билет";
:Ввод данных пассажира;
:Отображение доступных мест;
if (Есть свободные места?) then (да)
    :Назначить место;
    :Сгенерировать номер бронирования;
else (нет)
    :Отобразить сообщение "Места недоступны";
endif
stop
@enduml
